### ISSUE TITLE
scorecard-webapp does not handle github/codeql-action@v2

### ISSUE THREAD

**Issue by aeisenberg** [ossf/scorecard-webapp#517]
[Here](https://github.com/ossf/scorecard-webapp/blob/main/app/server/verify_workflow.go#L269), this action has a special case for codeql-action@v1 since there are some commits in v1 that are not in main. We have recently released v3 and now v2 has commits that are not in main. This is causing some trouble with your action. See the issue: https://github.com/github/codeql-action/issues/2040

**Comment by spencerschrock** [comment]
Yes this is a limitation to how Scorecard webapp tries to associate a commit to a repo using the API GitHub provides, and not the fault of anything in this repo. Taking a look now

**Comment by spencerschrock** [comment]
Need to push from staging to prod before this is actually fixed

**Comment by aeisenberg** [comment]
Thanks for the quick turnaround. This will be a problem in the future when we release `v4` and future major versions.

**Comment by spencerschrock** [comment]
> Thanks for the quick turnaround. This will be a problem in the future when we release `v4` and future major versions.

We've have had a fix in mind, the problem is it depends on an unofficial endpoint, which we're not trying to rely on:
`https://github.com/<owner>/<repo>/branch_commits/<sha>`. Here's an example for the `github/codeql-action` commit which only exists in `releases/v2`:
https://github.com/github/codeql-action/branch_commits/03e7845b7bfcd5e7fb63d1ae8c61b0e791134fab

Is there any recommended channel for these sort of API requests? Someone already made a [GitHub community discussion which asks for it to be an official API](https://github.com/orgs/community/discussions/78161), but I can't say I've seen any of the discussions I've followed over the last two years get a response.

**Comment by aeisenberg** [comment]
I will reach out to the team that maintains this API internally to see if they are willing to make this API public, but I can't guarantee that they will or what the timeline would be. I don't have any other suggestions that come to mind right now. I will put in our notes to raise an issue in this repository when we release new versions of the action in the future.

**Comment by spencerschrock** [comment]
> I will reach out to the team that maintains this API internally to see if they are willing to make this API public, but I can't guarantee that they will or what the timeline would be.

Appreciate it, and of course whatever happens happens.

> I don't have any other suggestions that come to mind right now.

If they come back and can't publicize the API, we would probably fetch all of the release branches via the API instead of hardcoding it, and query in order of more recent versions until the request times out. (e.g. v3, then v2, then v1).

> I will put in our notes to raise an issue in this repository when we release new versions of the action in the future.

Long term, I'd like to avoid putting this burden on you. But appreciate it for now.
